version: '3.1'

services:

  mongo:
    image: mongo:4.2.12
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root

  rabbitmq:
    image: rabbitmq:3.8.14-management
    restart: unless-stopped
    ports:
      - 5672:5672 # Node Port
      - 15672:15672 # Management Port
